/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyxe;

//import com.mysql.cj.api.jdbc.Statement;
import java.awt.List;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */

public class formQLX extends javax.swing.JFrame {

    
     DefaultTableModel model;
    public formQLX() throws IOException {
        
        
        initComponents();
        model = (DefaultTableModel) tb_QLX.getModel();
        XH.docFileXE();
        hienThi();
    }
   private int iMaxe = 1;
    private String MaXe = "MODE" + iMaxe;
    
//    
//    public void loadData()
//    {
//        try {
//            DBconnection DB = new DBconnection();
//            Connection conn = DB.getconnection();
//            int number;
//            Vector row, column = null;
//            Statement st = conn.createStatement();
//            ResultSet rs = st.executeQuery("SELECT * FROM XE");
//            ResultSetMetaData metadata = rs.getMetaData();
//            number = metadata.getColumnCount(); //tra ve so cot
//            
//            for (int i = 1; i < number; i++) {
//                column.add(metadata.getColumnName(i)); //Lay ten cac cot
//            }
//            model.setColumnIdentifiers(column);
//            while(rs.next()) {
//                row = new Vector();
//                for (int i = 1; i < number; i++) {
//                    row.addElement(rs.getString(i));
//                    
//                }
//                model.addRow(row);
//                tb_QLX.setModel(model);
//            }
//        } catch (Exception e) {
//            System.out.println(e.toString());
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQL = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_QLX = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtMa = new javax.swing.JTextField();
        txtN = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtLoai = new javax.swing.JTextField();
        cboMau = new javax.swing.JComboBox();
        btnSort = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        cboHSX = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQL.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car3.png"))); // NOI18N
        lblQL.setText(" QUẢN LÝ XE HƠI");

        btnThem.setBackground(new java.awt.Color(204, 204, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/them.png"))); // NOI18N
        btnThem.setText(" THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(204, 204, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xóa.png"))); // NOI18N
        btnXoa.setText(" XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(204, 204, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/luu.png"))); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(204, 204, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sua.png"))); // NOI18N
        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(204, 204, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thoat.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timkiem.png"))); // NOI18N
        btnTimKiem.setText("TÌM KIẾM");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tb_QLX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Xe", "Tên Xe ", "Loại Xe", "NSX", "Màu", "HSX", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_QLX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_QLXMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_QLX);

        jLabel1.setText("Mã Xe");

        lbl2.setText("Tên Xe");

        lbl3.setText("Loại Xe");

        lbl4.setText("NSX");

        lbl5.setText("HSX");

        lbl6.setText("Màu");

        lbl7.setText("Giá");

        cboMau.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Xanh ", "Đỏ", " Đen" }));

        btnSort.setBackground(new java.awt.Color(204, 204, 255));
        btnSort.setText("Sắp Xếp");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        cboHSX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suziki", "Toyota", "Ferrari", "Lamborghini", "Vinfast", "Mazda" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(lblQL)
                .addGap(0, 335, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLoai))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl5)
                            .addComponent(lbl6)
                            .addComponent(lbl4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtN, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(cboMau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboHSX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGia))
                    .addComponent(btnSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblQL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbl7)
                            .addComponent(lbl4)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl5)
                            .addComponent(lbl2)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboHSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl6)
                            .addComponent(lbl3)
                            .addComponent(txtLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnSort, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     ListXeHoi XH = new ListXeHoi();
     public XeHoi khoiTao(){
        String MaXe  = txtMa.getText();
         String tenXe  = txtTen.getText();
         String loaiXe  = txtLoai.getText();
         String NSX  = txtN.getText();
         String HSX  = cboHSX.getSelectedItem().toString();
         String Mau  = cboMau.getSelectedItem().toString();
         double Gia  = Double.parseDouble(txtGia.getText());
         
        
        XeHoi xh = new XeHoi(MaXe, tenXe, loaiXe, NSX, Mau, HSX,  Gia);
        return xh;
    }
    
    public void hienThi(){ 
        model.setRowCount(0);
        for (XeHoi xh : XH.select() ) {
            model.addRow(new Object[] { xh.getMaxe(), xh.getTenXe(), xh.getLoaiXe(), xh.getNSX(),xh.getMau(), xh.getHSX(),  xh.getGia()});
        }
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
         //XH.add(khoiTao());
        // hienThi();
        
         try {
            if (txtMa.getText().length() == 0 || txtTen.getText().length() == 0 || txtLoai.getText().length() == 0 || cboHSX.getSelectedItem().toString().length() == 0|| txtN.getText().length() == 0|| txtGia.getText().length() == 0) {
                JOptionPane.showConfirmDialog(rootPane, "Không được để trống!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                // kiem tra ma 
                boolean flagMaCT = true;
                for (XeHoi xh : XH.select()) {
                    if (txtMa.getText().equals(xh.getMaxe())) {
                        flagMaCT = false;
                        break;
                    }
                }
                if (flagMaCT) {
                    XH.add(khoiTao());
                    hienThi();                   
                } else {
                    JOptionPane.showConfirmDialog(rootPane, "Mã xe đã tồn tại!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    txtMa.requestFocus(true);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(rootPane, "Dữ liệu không hợp lệ!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
         
    }//GEN-LAST:event_btnThemActionPerformed
  
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        //XH.update(khoiTao());
       //  hienThi();
        
        try {
            if (txtMa.getText().length() == 0 || txtTen.getText().length() == 0 || txtLoai.getText().length() == 0 || cboHSX.getSelectedItem().toString().length() == 0|| txtN.getText().length() == 0|| txtGia.getText().length() == 0) {
                JOptionPane.showConfirmDialog(rootPane, "Không được để trống!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                // kiem tra ma
                boolean flagMaCT = true;
                int index = tb_QLX.getSelectedRow();
                for (int i = 0; i < XH.select().size(); i++) {
                    XeHoi xh = new XeHoi();
                    xh = XH.select().get(i);
                    if (i != index) {
                        if (txtMa.getText().equals(xh.getMaxe())) {
                            flagMaCT = false;
                            break;
                        }
                    }
                }
                if (flagMaCT) {
                    // sua 
                    XH.update(khoiTao());
                    // update lai du lieu
                    hienThi();
                } else {
                    JOptionPane.showConfirmDialog(rootPane, "Mã xe đã tồn tại!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    txtMa.requestFocus(true);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(rootPane, "Dữ liệu không hợp lệ!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        model = (DefaultTableModel)tb_QLX.getModel(); 
        hienThi();
         if (txtTimKiem.getText() != null) {
         XeHoi xh = XH.find(txtTimKiem.getText());  
         model.setRowCount(0);
         
         model.addRow(new Object[] { xh.getMaxe(), xh.getTenXe(), xh.getLoaiXe(), xh.getNSX(),xh.getMau(), xh.getHSX(),  xh.getGia()});   
         
         }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
         int n = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc chắn muốn thoát?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            XH.ghiFileXE();
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        settext();
       
        
    }//GEN-LAST:event_btnResetActionPerformed
    public void settext()
    {
        txtMa.setText("");
        txtTen.setText("");
        txtLoai.setText("");
        
        txtN.setText("");
        txtGia.setText("");
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
         int[] index = tb_QLX.getSelectedRows();
        if (index.length <= 0) {
        } else {
            int n = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc chắn muốn xóa?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (n == 0) {
                int temp = 0;
                for (int i : index) {
                    model.removeRow(i - temp);
                    XH.delete1(i - temp);
                    temp++;
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        // TODO add your handling code here:
       XH.sortByName();
        hienThi();
    }//GEN-LAST:event_btnSortActionPerformed

    private void tb_QLXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_QLXMouseClicked
        // TODO add your handling code here:
        int index = tb_QLX.getSelectedRow();
        XeHoi xh = new XeHoi();
            xh  = XH.select().get(index);
            txtMa.setText(xh.getMaxe());
            txtTen.setText(xh.getTenXe());
            txtLoai.setText(xh.getLoaiXe());
            txtN.setText(xh.getNSX());
            txtGia.setText(String.valueOf(xh.getGia()));
    }//GEN-LAST:event_tb_QLXMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formQLX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formQLX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formQLX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formQLX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new formQLX().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(formQLX.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSort;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox cboHSX;
    private javax.swing.JComboBox cboMau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lblQL;
    private javax.swing.JTable tb_QLX;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtLoai;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
